package druyaned.corejava.vol1.ch08.src;

import static druyaned.ConsoleColors.blueBold;
import static druyaned.ConsoleColors.bold;
import druyaned.corejava.vol1.ch05.ClassAnalyzer;

public class TestBridgeMethod {
    
    public static void run() {
        System.out.println("\n" + bold("TestBridgeMethod"));
        StringSayer sayer = new StringSayer();
        String message =
                blueBold("NOTE") + "! There are 2 methods, so the method " +
                "with an Object parameter is generated by the compiler.";
        sayer.say(message);
        ClassAnalyzer.showClass(sayer.getClass());
    }
    
}
