package com.github.druyaned.learn_java.vol1.chapter08;

import static com.github.druyaned.ConsoleColors.bold;
import com.github.druyaned.learn_java.vol1.chapter05.ClassAnalyzer;

public class BridgeMethodTester {
    public static void run() {
        System.out.println("\n" + bold("Testing bridge method."));

        StringSayer sayer = new StringSayer();
        String message = "NOTE! There are 2 methods, so the method with " +
                         "an Object parameter is generated by the compiler.";
        sayer.say(message);

        ClassAnalyzer.showClass(sayer.getClass());
    }
}

class Sayer<T> {
    public String say(T message) {
        System.out.println("Saying: " + message.toString());
        return message.toString();
    }
}

class StringSayer extends Sayer<String> {
    @Override // A little fake
    public String say(String message) {
        System.out.println("Saying: " + message);
        return message;
    }
}
