package druyaned.corejava.vol1.ch08generics;

import static druyaned.ConsoleColors.blueBold;
import druyaned.corejava.Chapter;
import druyaned.corejava.Topic;
import druyaned.corejava.vol1.ch05inherit.ClassAnalyzer;
import druyaned.corejava.vol1.ch08generics.t01bridge.StringSayer;

public class T01BridgeMethod extends Topic {
    
    public T01BridgeMethod(Chapter chapter) {
        super(chapter, 1);
    }
    
    @Override public String title() {
        return "Topic 01 BridgeMethod";
    }
    
    @Override public void run() {
        StringSayer sayer = new StringSayer();
        String message = blueBold("NOTE") + "! There are 2 methods, so the"
                + " method with an Object parameter is generated by the compiler.";
        sayer.say(message);
        ClassAnalyzer.showClass(sayer.getClass());
    }
    
}
